### ISSUE TITLE
How to include shim with JSPM?

### ISSUE THREAD

**Issue by Quirksmode** [danialfarid/ng-file-upload-shim-bower#1]
Hi, firstly thanks for this amazing plugin!!

I managed to get ng-file-upload working nice and easily with JSPM, but I am struggling with how I can include the ng-file-upload shim as a dependancy as I need this to support IE9.

```
System.config({
  "map": {
    "angular": "github:angular/bower-angular@1.4.3",
    "ng-file-upload": "github:danialfarid/ng-file-upload-bower@6.0.3",

    // Declare dependancy
    "github:danialfarid/ng-file-upload-bower@6.0.3": {
      "ng-file-upload-shim": "github:danialfarid/ng-file-upload-shim-bower@6.0.3"
    },
})
```

Does this look right to you as it doesn't seem to pull in the shim, is there an easier way to do this e.g. just reference the ng-file-upload-all.js file that seems to be available?

Any help is greatly appreciated

**Comment by danialfarid** [comment]
Load shim before the plugin. And yes you could use -all which is a merge of those two files but there is no bower for it.

**Comment by Quirksmode** [comment]
Thanks, I fixed it with the following:

"ng-file-upload": "github:danialfarid/ng-file-upload-bower@6.0.3/ng-file-upload-all",

**Comment by danialfarid** [comment]
Great!
